### PR TITLE
Refactor the gem setup for CukeSalad

### PR DESCRIPTION
**Pull request by JonRowe**
Hi
I hope you don't mind but I've taken the liberty of tidying this up a bit as a gem.

I've switched the build process from Jeweller to [Bundler](http://gembundler.com/rubygems.html) mainly so theres an explicit gemspec, and have modified the Gemfile to match [wycats recommendations for Gemfiles for gems](http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/). I guess this is a personal preference but I've found building gems a lot easier with bundler.

I've also moved most of the files into the `cukesalad` folder within lib, and name spaced them accordingly into the `CukeSalad` module in order to avoid conflicts in the global lib path, Rails actually has a [pretty good blog post about this](http://weblog.rubyonrails.org/2009/9/1/gem-packaging-best-practices)

Also I've not done anything about this, but doesn't having the `in_order_to` method in the top level scope mean that we're sacrificing the isolation `Cucumber::World` provides between scenarios/steps?

### CODE REVIEW

**Comment by antonymarcano** [comment]
Thanks Jon. We really appreciate your contribution. We'll take a look in the next few days.

Regarding having `in_order_to` in the top-level scope... That's a good point, although we've not encountered a problem with that so far. Do you have a suggestion on implementing it with the isolation and allowing us to create the tasks as simply as we do currently?

```
in_order_to 'do something' do
    # the actions
end
```

**Comment by JonRowe** [comment]
"Do you have a suggestion on implementing it with the isolation and allowing us to create the tasks as simply as we do currently?" 

Not as a specific implementation but something along the lines of mixing a CukeSalad world into the world used by cucumber, so that tasks are performed within the world. Not quite sure how it'd work, and it might be something for the future if aslak makes cucumber more plug in able.

**Comment by antonymarcano** [comment]
Hi Jon,
Finally I've got round to pulling this to test and merge.
Did you write a gemspec? I'm guessing that you probably did but maybe it didn't get committed.

Despo's original Jeweller gemification generated the gemspec. Because it was generated we added it to .gitignore.

Do let us know. If not, I can always write it myself... but handy if you've already done it.

Thanks

Antony

**Comment by JonRowe** [comment]
Arf, you're right, it has been ignored by the .gitignore, I definitely wrote one but it's on my work machine so will have to wait till tomorrow. Doh!

**Comment by antonymarcano** [comment]
Many thanks Jon!

I threw in a fix for another issue and released as 0.6.1 :-)

Cheers

**Pull request merged**
