### PR TITLE
Bundled steps

### PR DESCRIPTION
**Pull request by despo**
Created a cucumber step that bundles up the role creation with a task that the role needs to perform as part of the setup.

We have found this very handy as it means less steps need to be written for the background task.

The downside is that the created task's wording is not great.

For example our step is:
Given I am a 'logged in' Web User

and the task:
in_order_to 'logged in' do
..
end

Any thoughts?
- Despo

### CODE REVIEW

**Comment by despo** [comment]
and also changed the require in cucumber_steps to only require the salad files and not itself.

**Comment by andypalmer** [comment]
Alias in_order_to to in_order_to_be 'logged in' do

**Comment by despo** [comment]
Thanks Andy.

Would you be interested in meging this functionality in? 

So should I include the alias in cukesalad as well?

**Comment by andypalmer** [comment]
It's not really my call to make, and I haven't had time to investigate
in great detail. I was just (hopefully) helping overcome the stumbling
language issue.

**Comment by despo** [comment]
:) Fair enough. I'll wait until Antony gets back to me then.

**Comment by antonymarcano** [comment]
Having discussed this pull request... it was closed because there's a better way of solving it.

If you have this:

```
module WebUser
  def methods_go_here
    # ...
  end
end
```

Then you can do this:

```
module LoggedInWebUser
  include WebUser
  def role_preparation
    #...special stuff a LoggedInWebUser does     
  end
end
```

**Pull request closed without merging**
